name: milunch_pos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  firebase_core_desktop: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  slide_digital_clock: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/items/
