// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAozx2mOrsIfJIUEinHsnvjly1WQGRsUWY',
    appId: '1:308257357534:web:96c5cb03bfdca648940c4f',
    messagingSenderId: '308257357534',
    projectId: 'milunchpos',
    authDomain: 'milunchpos.firebaseapp.com',
    storageBucket: 'milunchpos.appspot.com',
    measurementId: 'G-Y850MG2GCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEcSTmbadirIs6A4aIaqoiHVF-BPMBSI8',
    appId: '1:308257357534:android:438f6f844d807c77940c4f',
    messagingSenderId: '308257357534',
    projectId: 'milunchpos',
    storageBucket: 'milunchpos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnPOWnOZ_HuJOQaWviONuO9V1jx7gd6Y4',
    appId: '1:308257357534:ios:4a368a5c18c86a0d940c4f',
    messagingSenderId: '308257357534',
    projectId: 'milunchpos',
    storageBucket: 'milunchpos.appspot.com',
    iosBundleId: 'com.example.milunchPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnPOWnOZ_HuJOQaWviONuO9V1jx7gd6Y4',
    appId: '1:308257357534:ios:dc2fbf96d6efc569940c4f',
    messagingSenderId: '308257357534',
    projectId: 'milunchpos',
    storageBucket: 'milunchpos.appspot.com',
    iosBundleId: 'com.example.milunchPos.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAozx2mOrsIfJIUEinHsnvjly1WQGRsUWY',
    appId: '1:308257357534:web:7f3f4a775b2bb2d5940c4f',
    messagingSenderId: '308257357534',
    projectId: 'milunchpos',
    authDomain: 'milunchpos.firebaseapp.com',
    storageBucket: 'milunchpos.appspot.com',
    measurementId: 'G-NM7YG04XS9',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAozx2mOrsIfJIUEinHsnvjly1WQGRsUWY',
    appId: '1:308257357534:web:b074e64566e54f1d940c4f',
    messagingSenderId: '308257357534',
    projectId: 'milunchpos',
    authDomain: 'milunchpos.firebaseapp.com',
    storageBucket: 'milunchpos.appspot.com',
    measurementId: 'G-7G1WW0JSP8',
  );
}
